from SBOM_generate import SBOM_generate
from DeepAnalysis import DeepAnalysis
from CompareSBOMs import CompareSBOMs
from CompareLocalSBOMWithRemote import CompareLocalSBOMWithRemote
import json
import asyncio
import aiohttp
       
       
 
   
async def main():
     gen=SBOM_generate()
     gen.generate_sbom()
     filesToAnalyze=gen.get_SBOMs()
     
     print("Select Way to analyze:")
     print("  0. All")
     print("  1. Deep Analysis")
     print("  2. Compare to Ground Truth")
     print("  3. None")    
     selection = input("Enter your choice: ").strip()
     choices = {"1": "deep", "2": "compare"}
     ground_truth=""
     selected_analysis = set(choices.values()) if "0" in selection else {choices[c] for c in selection.split(",") if c in choices}   
     if "compare" in selected_analysis:
        ground_truth_file = input("Directory to Ground Truth File: ").strip()
        ground_truth=CompareLocalSBOMWithRemote(ground_truth_file).getFileContents()
        
         
     print("Going to analyze : " + str(filesToAnalyze))
     for files in filesToAnalyze:
          with open(files, 'r') as file:
                fileContents = json.load(file)
          type="microsoft"
          if 'github' in files:
              type='GitHub'
          elif '_syft' in files:
              type='Syft'
          elif '_trivy' in files:
              type='Trivy'
          print("\n\n\n ***OUTPUT FOR THE SBOM GENERATED  BY " + type + "***\n\n\n")

          if 'sbom' in fileContents:
                fileContents=fileContents['sbom']
          if "deep"  in selected_analysis:
             analyzer=DeepAnalysis(fileContents)
             await analyzer.Analyze()
             missing_packs=analyzer.getMissingPacks()         
             print("Deep Analysis Results:\n\nThe SBOM generated by " + type +" is missing " + str(len(missing_packs)) + " dependencies\n")
          if "compare" in selected_analysis:
               print("Comparing to Ground Truth Results: \n\n")
               compares=CompareSBOMs(files)
               compares.setTruth(ground_truth)
               compares.setNonTruth(fileContents)
               compares.compareSBOMs()

    
      
       
       
        
if __name__ == "__main__":
        asyncio.run(main())
