from SBOM_generate import SBOM_generate
from DeepAnalysis import DeepAnalysis
import json
import asyncio
import aiohttp
       
       
 
   
async def main():
     gen=SBOM_generate()
     gen.generate_sbom()
     filesToAnalyze=gen.get_SBOMs()
     print("Going to analyze : " + str(filesToAnalyze))
     for files in filesToAnalyze:
          with open(files, 'r') as file:
                fileContents = json.load(file)
          if 'sbom' in fileContents:
                fileContents=fileContents['sbom']
          analyzer=DeepAnalysis(fileContents)
          await analyzer.Analyze()
          missing_packs=analyzer.getMissingPacks()
          type="microsoft"
          if 'github' in files:
              type='GitHub'
          elif '_syft' in files:
              type='Syft'
          elif '_trivy' in files:
              type='Trivy'
          print("The SBOM generated by " + type +" is missing " + str(len(missing_packs)) + " dependencies")
     
    
      
       
       
        
if __name__ == "__main__":
        asyncio.run(main())
